/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Double core
 * The Double API documentation
 * OpenAPI spec version: 1.0
 */

export type RefreshTokenDto = {
  refreshToken: string;
};
