/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Double core
 * The Double API documentation
 * OpenAPI spec version: 1.0
 */
import type { TokenTokenType } from './tokenTokenType';

export type Token = {
  accessExpireIn: string;
  accessToken: string;
  refreshExpireIn: string;
  refreshToken: string;
  tokenType: TokenTokenType;
};
