/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Double core
 * The Double API documentation
 * OpenAPI spec version: 1.0
 */

export type User = {
  createdAt: string;
  deletedAt?: string;
  /** @nullable */
  firstName?: string | null;
  id: string;
  /** @nullable */
  lastName?: string | null;
  readonly name: string;
  password?: string;
  telegramId?: string;
  updatedAt: string;
};
